### ISSUE TITLE
Updating the examples for 3.x compatibility

### ISSUE THREAD

**Issue by dominic-p** [oauthjs/express-oauth-server#10]
The examples in this repo have been very helpful to me in trying to understand exactly what is expected of a Model. However, when I look at the [Migrating from 2.x to 3.x guide](https://github.com/oauthjs/node-oauth2-server/wiki/Migrating-from-2.x-to-3.x), it seems like the model specifications have changed. Would it be possible to update the examples here accordingly? Thanks, btw, for sharing this code.

**Comment by manjeshpv** [comment]
3.0.0-b2 compatibile Implementation with SQL and NoSQL https://github.com/manjeshpv/node-oauth2-server-implementation

**Comment by dominic-p** [comment]
Thanks for doing that. Those examples will be very helpful.
