### ISSUE TITLE
Fix 'Quick Start' documentation

### ISSUE THREAD

**Issue by richorton** [oauthjs/express-oauth-server#27]
Hey,

Just a head's up that the 'Quick Start' documentation has a minor mistake which could potentially cause a few headaches :)

`app.use(app.oauth.authorise());`

should be changed to be...

`app.use(app.oauth.authorize());`

Thanks!

**Comment by blingz** [comment]
z not s

**Comment by mlasevich** [comment]
Also case issues  - bodyParser != bodyparser

**Comment by ruimarinho** [comment]
Thanks, landed in https://github.com/oauthjs/express-oauth-server/commit/2274bf1d2b1f5af1914e567502b523525a68ddb1.
