### ISSUE TITLE
ExpressOAuthServer should wrap containing functions

### ISSUE THREAD

**Issue by chainlink** [oauthjs/express-oauth-server#32]
`ExpressOAuthServer` should wrap containing functions in a closure to ensure `this` is properly scoped. Currently it's making use of module scope, but a closure is more straight forward and portable (I'm currently using the ExpressOAuthServer directly in my server implementation)

https://github.com/oauthjs/express-oauth-server/blob/master/index.js#L17

**Comment by maxtruxa** [comment]
Sorry, I don't quite get what you're aiming at.. Could you elaborate?

**Comment by chainlink** [comment]
Fixed!
