### ISSUE TITLE
Storing authentication information between middlewares

### ISSUE THREAD

**Issue by steffansluis** [oauthjs/express-oauth-server#4]
Currently, after calling node-oauth2-server handlers, some results are exposed via `req.app.locals`. As stated [here](http://expressjs.com/en/api.html#app.locals), this persists throughout the lifetime of the application. `res.locals` only persists throughout the lifetime of the current request. It seems to me the second option should be used, since authentication is request specific. Is this an intentional decision?

**Comment by nunofgs** [comment]
Not intentional at all. Nice catch :)

You can submit a PR if you'd like. Otherwise I'll fix it soon.
