### ISSUE TITLE
mongodb examples broken: oauth-server expecting docs, receives mongoose wrapper instead

### ISSUE THREAD

**Issue by ancamcheachta** [oauthjs/express-oauth-server#45]
Attempting to use the mongodb example out of the box, I ran into the following behaviour when debugging /oauth-server/lib/models/token-model.js:

![stack trace](https://s9.postimg.org/7r93g8nnj/client_grants_missing.png)

As you can see above, many properties appear to be missing as the example model functions (in this case `getClient()`) return a mongoose object rather than the document itself.  Instead, we see that the document is buried one level deeper within this object under the `_doc` property, and that `grants`, etc. are to be found there.  Assuming the common use of leading underscore indicates private use here, and noting the mongoose documentation on it is lacking, it would be nice to rely on something more robust.

It turns out that `lean()` can be chained to most, perhaps all of the queries in this file, returning just the document.  The only special case is `saveAccess()`, but using `Promise` along with some fairly explicit logic to prepare [the return values expected by the oauth server](https://github.com/oauthjs/node-oauth2-server/wiki/Model-specification#password-grant) I was able to implement a fix: https://github.com/ancamcheachta/express-oauth-server/commit/5f98bd18a361cb8f6239d54024fe0ccf76503f51.

Pull request including commit in question is forthcoming, however would be interested in future of support for mongodb example.  Did a previous version of mongoose work with the example?  If so, which version?  If there is a specific version, would it be worth noting in the readme for mongodb and suggesting that version be frozen using `package.json`?  Or are would ye rather the fix?  Sure have a look at the pull request, anyway.

**Comment by dman777** [comment]
can you re-open? this is still a issue
