### ISSUE TITLE
Incomplete exemple

### ISSUE THREAD

**Issue by deblockt** [oauthjs/express-oauth-server#60]
Hello, 

I'm trying to run the postgres exemple, but this doesn't work.
   - templates are missing
   - postgres connection doesn't work

I have successful create template and correct postgres connection, but i don't understand who it's work.
   - have a the input /oauth/authorize who redirect to login
   - with login, i can input username. form send a post request to /login
   - i check the username/(password)
   - At this step i don't know, what i must do. I have try to call authorize but this doesn't work because there are no token provided, if i add a simple token like "azerty", authorize so model.getAccessToken is called before model.saveAccessToken, so this doesn't work.

Can you provide a real and functional sample, with login/authorize/ getToken exemple?

**Comment by waychan23** [comment]
check this out: https://github.com/waychan23/koa2-oauth-server/tree/master/examples/complete-example
